// Base des pièces justificatives (Annexe B). Source : mémo interne
// « Documents à prendre pour les RDV écrivains publics ». Affichée à la personne
// en fin d'entretien pour préparer le RDV suivant (étape 5).

export const PIECES_JUSTIFICATIVES: Record<string, string[]> = {
  cni_passeport: [
    'Adresse mail + mot de passe du compte mail (si existant)',
    'État civil complet des deux parents (noms, prénoms, dates et lieux de naissance) ou livret de famille / actes de naissance',
    'Taille et couleur des yeux',
    'Justificatif de domicile < 6 mois',
    'Savoir pourquoi on est français (mariage, déclaration, décret, filiation)',
    'Passeport : timbre fiscal acheté en amont — 17 € (<15 ans), 42 € (15-18), 86 € (majeur)',
    'Perte/vol CNI : timbre fiscal 25 €',
  ],
  handi_stat: [
    "Certificat d'immatriculation",
    'Justificatif de résidence < 6 mois',
    'Attestation MDPH mention « stationnement » ou carte CMI-S',
  ],
  css: ["Avis d'imposition de chaque membre du foyer (ou avis de situation)"],
  ame: [
    "Photos d'identité de chaque membre du foyer",
    "Pièce d'identité de chaque membre (passeport / CNI / ancien titre de séjour / livret de famille / acte de naissance / autre)",
    'Résidence >3 mois : passeport avec date d’entrée (toutes pages) OU bail/quittance >3 mois OU facture énergie/eau >3 mois OU avis d’impôt/taxe foncière',
    'Sans domicile propre : attestation CHRS >3 mois',
    "Hébergé chez un tiers : facture au nom de l'hébergeant >3 mois OU attestation de domiciliation organisme agréé >3 mois",
    'Justificatifs de ressources du foyer sur 12 mois',
  ],
  puma: [
    'Formulaire S1106 / CERFA 15763*01',
    'Copie passeports + titres de séjour ou visa de tous les majeurs (hors réfugiés/apatrides/PS)',
    'Acte de naissance de tous les membres du foyer',
    'Livret de famille si existant',
    'Si activité : contrat de travail + 3 derniers bulletins',
    'Si critère résidence ≥3 mois : bail + 3 quittances OU attestation d’hébergement OU attestation structure sociale OU 3 dernières factures',
  ],
  rattachement_enfants: [
    'Formulaire S3705 / CERFA 14445*02',
    'Acte de naissance des enfants ou livret de famille',
  ],
  aide_cpam_8101: [
    'Formulaire 8101',
    "Dernier avis d'imposition de chaque membre (si couple non marié)",
    'Si changement de situation : justificatifs de ressources des 3 derniers mois',
    'DENTAIRE : facture ou 2 devis <6 mois + prise en charge complémentaire',
    'OPTIQUE/AUDITIF : ordonnance + facture/devis + prise en charge complémentaire',
    'HOSPITALISATION : facture/devis ou avis de sommes à payer + prise en charge complémentaire',
  ],
  rsa_prime_activite: [
    'État civil de chaque membre (UE : CNI/passeport/titre ; hors UE : titre en cours + acte de naissance intégral)',
    'Enfant <18 ans : acte de naissance (RSA) / certificat OFII ou attestation préfectorale (PA)',
    'Enfant >18 ans : titre de séjour',
    'Réfugié/apatride/PS : titre OU récépissé mention réfugié OU décision OFPRA/CNDA',
    'RIB (+ RIB conjoint)',
    'Non-salarié : formulaire complémentaire ; retraité : dernier avis de pension',
    'Domiciliation : attestation de l’organisme',
  ],
  asf: [
    'Enfant non reconnu : acte de naissance <3 mois',
    'Pension non fixée : justificatif d’engagement de procédure (ASF versée 4 mois max)',
    'Jugement sans pension : copie du jugement',
    'Pension fixée non payée : titre fixant la pension + AR de notification / acte d’huissier',
    'Violences de l’autre parent : document officiel (plainte, jugement…)',
  ],
  aspa: [
    'Dernier avis d’impôt + celui du conjoint',
    'Justificatif de résidence en France du mois de la demande',
    'Justificatifs de ressources des 3 derniers mois (retraites, pensions, CAF)',
    'Preuve de présence 9 mois/an (factures, relevés, tampons passeport, soins)',
    'Hors UE : titres autorisant à travailler sur les 10 dernières années',
    'Apatride/réfugié/PS : décision OFPRA/CNDA',
  ],
  mdph: [
    'Justificatif d’identité + justificatif de domicile',
    'Certificat médical MDPH',
    'Pension d’invalidité/rente AT-MP : justificatif',
    'Enfant scolarisé : GEVASco ; temps partiel : contrat de travail',
  ],
  dls: [
    'CERFA complété et signé',
    'Pièce d’identité + régularité du séjour (hors UE) de tous les majeurs à loger',
    'Avis d’imposition (ou non-imposition) des personnes à loger',
    'Situation familiale : livret de famille / actes de naissance / jugement / mode de garde',
    'Situation pro : contrat de travail',
    'Ressources 3 derniers mois : attestation CAF, bulletins, attestation retraite',
    'Logement actuel : domiciliation / attestation hôtel / attestation hébergeant + facture + pièce d’identité / bail',
  ],
  dalo: [
    'Tout le dossier DLS',
    'DLS active actualisée (n° INE)',
    'Décision COMED si recours déjà déposé',
  ],
  apl: [
    'Adresse mail valide (+ mot de passe si possible)',
    'Pièce d’identité (CNI/passeport/titre)',
    'Carte Vitale ou attestation de droits',
    'Bail',
    'Coordonnées du bailleur + montant du loyer + SIRET si société',
    'Relevés de comptes (patrimoine/épargne) du foyer',
    'RIB',
  ],
  pef: [
    'Justificatif d’identité (CNI/passeport/titre en cours)',
    '3 avis d’imposition à l’adresse parisienne (3 ans de présence sur 5)',
    'Facture d’électricité et/ou gaz au nom du demandeur',
  ],
  casvp_pack_familles: [
    'FR : CNI ou passeport / autres : justificatif de droit au séjour en cours',
    'Présence à Paris : 3 avis d’imposition à l’adresse parisienne (ou 3 quittances + 3 factures énergie/an, etc.)',
    'Versement : RIB au nom du demandeur (ou autorisation de versement à un tiers + son RIB)',
    'Selon situation : livret de famille, jugement, garde alternée, dernière déclaration de revenus',
    'Ressources : dernier avis d’imposition intégral + justificatifs récents + justificatif versement/non-versement AL',
  ],
  carte_familles_nombreuses: [
    'Pièce d’identité des adultes',
    'Actes de naissance des enfants ou livret de famille',
    'Photo d’identité de chaque personne',
    'Dernier avis d’imposition',
    'Dernière attestation CAF',
  ],
  solidarite_transport: [
    '1re demande : carte Navigo éditée en guichet',
    'Renouvellement : carte Navigo + mail et mot de passe',
    'Justificatif de droits : AME / CSS sans participation / attestation RSA / carte d’invalidité',
  ],
  imagine_r_junior: [
    'Photo d’identité récente',
    'Justificatif d’identité de l’enfant (acte de naissance, DCEM, passeport, CNI)',
    'Carte bancaire (24,80 €)',
  ],
  imagine_r_scolaire: [
    'Photo d’identité récente',
    'Justificatif d’inscription ou de scolarité',
    'Justificatifs de demande/notification de bourse',
    'Nom exact de l’établissement + classe',
    'Carte bancaire (392,30 €) — remboursable 100 % Ville de Paris',
  ],
  dcem: [
    'E-photo avec numéro',
    'Passeport (réfugiés : acte de naissance OFPRA + décision de protection, PAS de passeport)',
    'Livret de famille',
    'Certificat de présence (scolarité/crèche) année en cours',
    'Justificatif de domicile <6 mois',
    'Acte de naissance complet',
  ],
  carte_resident_renouvellement: [
    'Passeport : pages état civil + tous visas/cachets',
    'E-photo',
    'Justificatif de domicile <6 mois',
    'Résidence habituelle 3 ans (6 mois/an) : bulletins/contrats, transport, avis d’imposition, factures, scolarité',
  ],
  naturalisation: [
    'Pièce(s) d’identité de la/des nationalité(s) en cours',
    'Titre de séjour recto/verso',
    'Langue : diplôme ≥ niveau 3 ou B2 / TCF-TEF <2 ans / attestation Enic-Naric',
    'Acte de naissance intégral avec filiation (+ traduction)',
    'Fiscal : avis d’imposition 3 ans + bordereau P.237 <3 mois',
  ],
  regroupement_familial: [
    'Formulaire OFII + toutes pièces en recommandé (garder copie complète)',
    'Titre de séjour en cours + présence régulière 18 mois',
    'Logement zone A : 22 m² (2 pers.) +10 m²/pers. supp.',
    'Ressources 12 mois (≈ SMIC selon taille du foyer ; prestations familiales exclues sauf AAH)',
    'Famille hors de France ; regroupement TOTAL',
  ],
};
